name:                nlp-hs
version:             0.1.0.0
github:              "s1m0000n/nlp-hs"
license:             BSD3
author:              "Semyon Pogoreltsev"
maintainer:          "pogorelcevsa@gmail.com"
copyright:           "2023 Semyon Pogoreltsev"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/nlp-hs#readme>

dependencies:
- base >= 4.7 && < 5
- partial-semigroup
- text
- text-builder
- vector
- vector-algorithms
- ordered-containers
- unordered-containers
- text-trie
- text-metrics
- time
- regex
- cond
- hashable

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -O2
- -XFlexibleInstances
- -fexpose-all-unfoldings
- -fspecialise-aggressively
- -fasm-shortcutting
- -feager-blackholing
- -fexcess-precision
- -ffun-to-thunk
- -flate-dmd-anal
- -fspec-constr-keen
- -flate-specialise
- -fstatic-argument-transformation

library:
  source-dirs: src

executables:
  nlp-hs-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - nlp-hs

tests:
  nlp-hs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - nlp-hs
